version: '3.3'

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      - auth_server

  auth_server:
    restart: always
    build: ./AuthServer
    ports:
      - "8000:8000"

  resource_server:
    restart: always
    build: ./ResourceServer
    ports:
      - "8001:8001"
